// STARSPACKS
export const GET_ALL_STARS_PACKS = 'GET_ALL_STARS_PACKS'

// CARDSPACK

export const GET_ALL_CARDS_PACKS = 'GET_ALL_CARDS_PACKS'
export const BUY_CARD_PACK = 'BUY_CARD_PACK'

// SHOPCART
export const ADD_TO_SHOPCART = 'ADD_TO_SHOPCART'
export const REMOVE_FROM_SHOPCART= 'REMOVE_FROM_SHOPCART'
export const GET_PREFERENCE_ID = 'GET_PREFERENCE_ID'

// CARDS
export const GET_ALL_CARDS = 'GET_ALL_CARDS'
export const FILTER_CARDS = 'FILTER_CARDS'
export const SORT_CARDS = 'SORT_CARDS'
export const SEARCH_CARD = 'SEARCH_CARD'
