// STARSPACKS
export const GET_ALL_STARS_PACKS = 'GET_ALL_STARS_PACKS';

// CARDSPACK

export const GET_ALL_CARDS_PACKS = 'GET_ALL_CARDS_PACKS';
export const BUY_CARD_PACK = 'BUY_CARD_PACK';
export const CLEAN_MSG_INFO = 'CLEAN_MSG_INFO';
export const FILTER_CARDS_PACKS = 'FILTER_CARDS_PACKS';

// SHOPCART
export const ADD_TO_SHOPCART = 'ADD_TO_SHOPCART';
export const REMOVE_FROM_SHOPCART= 'REMOVE_FROM_SHOPCART';
export const GET_PREFERENCE_ID = 'GET_PREFERENCE_ID';
export const SHOPCART_BUY_CARDSPACKS = 'SHOPCART_BUY_CARDSPACKS';
export const SHOPCART_CLEAN_MSG_INFO = 'SHOPCART_CLEAN_MSG_INFO';

// USER
export const GET_USER = 'GET_USER'
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const CREATE_USER = 'CREATE_USER'
export const SIGN_IN = 'SIGN_IN'
export const DELETE_USER = 'DELETE_USER'
export const MODIFY_USER = 'MODIFY_USER'
export const SET_TOKEN = 'SET_TOKEN'
// CARDS
export const GET_ALL_CARDS = 'GET_ALL_CARDS'
export const FILTER_CARDS = 'FILTER_CARDS'
export const SORT_CARDS = 'SORT_CARDS'
export const SEARCH_CARD = 'SEARCH_CARD'
export const GET_OPINIONS = 'GET_OPINIONS'
export const POST_OPINIONS = 'POST_OPINIONS'
export const CARD_DETAIL = 'CARD_DETAIL'
