const zergCards = [
  {
    name: "Zergling",
    Gdmg: 10,
    Admg: 0,
    life: 70,
    ability: "Atacante: gana 4.1 de daño terrestre.",
    abilities: [],
    race: "Zerg",
    cost: 50,
    movement: "Ground",
    image: "https://i.ibb.co/fry7vwF/Zergling.jpg",
  },
  {
    name: "Roach",
    Gdmg: 11.2,
    Admg: 0,
    life: 145,
    ability: "Defensor: gana 14.5 de vida.",
    abilities: [],
    race: "Zerg",
    cost: 125,
    movement: "Ground",
    image: "https://i.ibb.co/CQbZWyD/Roach.jpg",
  },
  {
    name: "Queen",
    Gdmg: 11.3,
    Admg: 12.7,
    life: 150,
    ability: "Atacante: gana 75 de vida. Defensor: repara 75 la base.",
    abilities: [],
    race: "Zerg",
    cost: 150,
    movement: "Ground",
    image: "https://i.ibb.co/ZWv6PdB/Queen.jpg",
  },
  {
    name: "Hydralisk",
    Gdmg: 22.2,
    Admg: 22.2,
    life: 90,
    ability: "Sin habilidad.",
    abilities: [],
    race: "Zerg",
    cost: 200,
    movement: "Ground",
    image: "https://i.ibb.co/1dTNLvB/Hydralisk.jpg",
  },
  {
    name: "Ravager",
    Gdmg: 14,
    Admg: 0,
    life: 120,
    ability:
      "Atacante: daña 60 la base enemiga. Defensor: gana 10 de daño terrestre.",
    abilities: [],
    race: "Zerg",
    cost: 300,
    movement: "Ground",
    image: "https://i.ibb.co/Qd2LY8m/Ravager.jpg",
  },
  {
    name: "Baneling",
    Gdmg: 0,
    Admg: 0,
    life: 0,
    ability:
      "Atacante: gana 40 de daño terrestre. Defensor: gana 80 de daño terrestre.",
    abilities: [],
    race: "Zerg",
    cost: 100,
    movement: "Ground",
    image: "https://i.ibb.co/XC97Kk6/Baneling.jpg",
  },
  {
    name: "Lurker",
    Gdmg: 14,
    Admg: 0,
    life: 200,
    ability:
      "Siempre: invisible. Atacante: daña 14 la base enemiga. Defensor: Gana 14 de daño terrestre.",
    abilities: [],
    race: "Zerg",
    cost: 450,
    movement: "Ground",
    image: "https://i.ibb.co/zFbG8Nz/Zerg-Lurker.jpg",
  },
  {
    name: "Defiler",
    Gdmg: 0,
    Admg: 0,
    life: 80,
    ability:
      "Siempre: daña 40 a los enemigos terrestres y aéreos. Atacante: daña 4 la base enemiga.",
    abilities: [],
    race: "Zerg",
    cost: 350,
    movement: "Ground",
    image: "https://i.ibb.co/1zPCh7P/Defiler.jpg",
  },
  {
    name: "Infestor",
    Gdmg: 0,
    Admg: 0,
    life: 90,
    ability: "Siempre: controla un enemigo aleatorio.",
    abilities: [],
    race: "Zerg",
    cost: 400,
    movement: "Ground",
    image: "https://i.ibb.co/4RJ8sdn/Infestor.jpg",
  },
  {
    name: "Swarm Host",
    Gdmg: 46.6,
    Admg: 0,
    life: 160,
    ability: "Siempre: invisible",
    abilities: [],
    race: "Zerg",
    cost: 250,
    movement: "Ground",
    image: "https://i.ibb.co/Gvr1xn9/Swarm-Host.jpg",
  },
  {
    name: "Ultralisk",
    Gdmg: 57.4,
    Admg: 0,
    life: 500,
    ability:
      "Atacante: gana 4.6 de daño terrestre. Defensor: gana 250 de vida.",
    abilities: [],
    race: "Zerg",
    cost: 700,
    movement: "Ground",
    image: "https://i.ibb.co/qgKybpV/Ultralisk.jpg",
  },
  {
    name: "Overlord",
    Gdmg: 0,
    Admg: 0,
    life: 200,
    ability: "Siempre: detector",
    abilities: [],
    race: "Zerg",
    cost: 100,
    movement: "Flying",
    image: "https://i.ibb.co/3rjnDs3/Overlord.jpg",
  },
  {
    name: "Scourge",
    Gdmg: 0,
    Admg: 220,
    life: 0,
    ability: "Sin habilidad.",
    abilities: [],
    race: "Zerg",
    cost: 175,
    movement: "Flying",
    image: "https://i.ibb.co/tq54zJw/Scourge.jpg",
  },
  {
    name: "Mutalisk",
    Gdmg: 8.3,
    Admg: 8.3,
    life: 120,
    ability:
      "Atacante: gana 11.3 de daño terrestre. Defensor: gana 40 de vida.",
    abilities: [],
    race: "Zerg",
    cost: 300,
    movement: "Flying",
    image: "https://i.ibb.co/SfvdDkj/Mutalisk.jpg",
  },
  {
    name: "Corruptor",
    Gdmg: 0,
    Admg: 10.3,
    life: 200,
    ability:
      "Atacante: daña 35 la base enemiga. Defensor: gana 4.4 de daño aéreo.",
    abilities: [],
    race: "Zerg",
    cost: 350,
    movement: "Flying",
    image: "https://i.ibb.co/kBqcpFs/Corruptor.jpg",
  },
  {
    name: "Viper",
    Gdmg: 0,
    Admg: 0,
    life: 150,
    ability:
      "Atacante: daña 35 la base enemiga. Defensor: disminuye el ataque aéreo enemigo un 10%",
    abilities: [],
    race: "Zerg",
    cost: 500,
    movement: "Flying",
    image: "https://i.ibb.co/pyxFPSj/Viper.jpg",
  },
  {
    name: "Brood Lord",
    Gdmg: 31.1,
    Admg: 0,
    life: 300,
    ability: "Atacante: gana 8.7 de daño terrestre. Defensor: gana 60 de vida.",
    abilities: [],
    race: "Zerg",
    cost: 800,
    movement: "Flying",
    image: "https://i.ibb.co/VMhsDW5/Brood-Lord.jpg",
  },
  {
    name: "Kerrigan",
    Gdmg: 75,
    Admg: 75,
    life: 1000,
    ability: "Sin habilidad.",
    abilities: [],
    race: "Zerg",
    cost: 1500,
    movement: "Ground",
    image: "https://i.ibb.co/8xxsrK5/Kerrigan.jpg",
  },
];

const terranCards = [
  {
    name: "Marine",
    Gdmg: 9.8,
    Admg: 9.8,
    life: 45,
    ability:
      "Atacante: gana 5.2 de daño terrestre y aéreo, y pierde 10 de vida.",
    abilities: [],
    race: "Terran",
    cost: 50,
    movement: "Ground",
    image: "https://i.ibb.co/S3GmsS1/Marine.jpg",
  },
  {
    name: "Marauder",
    Gdmg: 9.3,
    Admg: 0,
    life: 125,
    ability:
      "Atacante: gana 4.8 de daño terrestre y aéreo, y pierde 20 de vida.",
    abilities: [],
    race: "Terran",
    cost: 150,
    movement: "Ground",
    image: "https://i.ibb.co/Wyhvnx2/Marauder.jpg",
  },
  {
    name: "Ghost",
    Gdmg: 9.3,
    Admg: 9.3,
    life: 100,
    ability:
      "Atacante: invisible. Defensor: gana 80 de daño terrestre y aéreo.",
    abilities: [],
    race: "Terran",
    cost: 400,
    movement: "Ground",
    image: "https://i.ibb.co/16whCgL/Ghost.jpg",
  },
  {
    name: "Reaper",
    Gdmg: 10.1,
    Admg: 0,
    life: 60,
    ability: "Atacante: gana 75 de vida. Defensor: repara 75 la base.",
    abilities: [],
    race: "Terran",
    cost: 150,
    movement: "Ground",
    image: "https://i.ibb.co/rvdvJnB/Reaper.jpg",
  },
  {
    name: "Hellion",
    Gdmg: 4.5,
    Admg: 0,
    life: 90,
    ability:
      "Atacante: gana 3.4 de daño terrestre. Defensor: gana 6 de daño terrestre.",
    abilities: [],
    race: "Terran",
    cost: 100,
    movement: "Ground",
    image: "https://i.ibb.co/ChvNmYn/Hellion.jpg",
  },
  {
    name: "Vulture",
    Gdmg: 20,
    Admg: 0,
    life: 80,
    ability: "Sin habilidad.",
    abilities: [],
    race: "Terran",
    cost: 75,
    movement: "Ground",
    image: "https://i.ibb.co/k3Kq6hF/Vulture.jpg",
  },
  {
    name: "Widow Mine",
    Gdmg: 5.7,
    Admg: 5.7,
    life: 75,
    ability: "Defensor: invisible.",
    abilities: [],
    race: "Terran",
    cost: 125,
    movement: "Ground",
    image: "https://i.ibb.co/PZyh32z/Widow-Mine.jpg",
  },
  {
    name: "Goliath",
    Gdmg: 12,
    Admg: 20,
    life: 125,
    ability: "Sin habilidad.",
    abilities: [],
    race: "Terran",
    cost: 200,
    movement: "Ground",
    image: "https://i.ibb.co/SmGB80x/Goliath.jpg",
  },
  {
    name: "Siege Tank",
    Gdmg: 30,
    Admg: 0,
    life: 175,
    ability: "Atacante: daña 30 la base enemiga.",
    abilities: [],
    race: "Terran",
    cost: 400,
    movement: "Ground",
    image: "https://i.ibb.co/1fPj1PD/Siege-Tank.jpg",
  },
  {
    name: "Thor",
    Gdmg: 65.9,
    Admg: 11.2,
    life: 400,
    ability:
      "Atacante: gana 4.1 de daño terrestre. Defensor: gana 30 de daño aéreo.",
    abilities: [],
    race: "Terran",
    cost: 700,
    movement: "Ground",
    image: "https://i.ibb.co/b1xSpxf/Thor.jpg",
  },
  {
    name: "Medivac",
    Gdmg: 0,
    Admg: 0,
    life: 150,
    ability: "Siempre: gana 100 de vida terrestre.",
    abilities: [],
    race: "Terran",
    cost: 300,
    movement: "Flying",
    image: "https://i.ibb.co/47M3B2p/Medivac.jpg",
  },
  {
    name: "Viking",
    Gdmg: 16.9,
    Admg: 14,
    life: 125,
    ability: "Sin habilidad.",
    abilities: [],
    race: "Terran",
    cost: 300,
    movement: "Flying",
    image: "https://i.ibb.co/H2FqQTK/Viking.jpg",
  },
  {
    name: "Wraith",
    Gdmg: 8,
    Admg: 20,
    life: 120,
    ability: "Atacante: invisible.",
    abilities: [],
    race: "Terran",
    cost: 350,
    movement: "Flying",
    image: "https://i.ibb.co/kcZJfGQ/Wraith.jpg",
  },
  {
    name: "Banshee",
    Gdmg: 27,
    Admg: 0,
    life: 140,
    ability: "Atacante: daña 10 la base enemiga. Defensor: invisible.",
    abilities: [],
    race: "Terran",
    cost: 350,
    movement: "Flying",
    image: "https://i.ibb.co/mHMCYy2/Terran-Banshee.jpg",
  },
  {
    name: "Raven",
    Gdmg: 31.6,
    Admg: 31.6,
    life: 140,
    ability: "Siempre: detector.",
    abilities: [],
    race: "Terran",
    cost: 500,
    movement: "Flying",
    image: "https://i.ibb.co/0B9nBSs/Raven.jpg",
  },
  {
    name: "Liberator",
    Gdmg: 0,
    Admg: 7.8,
    life: 180,
    ability: "Defensor: gana 65.8 de daño terrestre.",
    abilities: [],
    race: "Terran",
    cost: 450,
    movement: "Flying",
    image: "https://i.ibb.co/G2rd908/Liberator.jpg",
  },
  {
    name: "Battlecruiser",
    Gdmg: 50,
    Admg: 31.3,
    life: 550,
    ability: "Atacante: daña 240 la base enemiga.",
    abilities: [],
    race: "Terran",
    cost: 1000,
    movement: "Flying",
    image: "https://i.ibb.co/sq9Bkk3/Battlecruiser.jpg",
  },
  {
    name: "Raynor",
    Gdmg: 75,
    Admg: 75,
    life: 1000,
    ability: "Sin habilidad.",
    abilities: [],
    race: "Terran",
    cost: 1500,
    movement: "Ground",
    image: "https://i.ibb.co/mzc7B81/Raynor.jpg",
  },
];

const protossCards = [
  {
    name: "Zealot",
    Gdmg: 18.6,
    Admg: 0,
    life: 150,
    ability: "Sin habilidad.",
    abilities: [],
    race: "Protoss",
    cost: 100,
    movement: "Ground",
    image: "https://i.ibb.co/tKtnNMD/Zealot.jpg",
  },
  {
    name: "Sentry",
    Gdmg: 8.5,
    Admg: 8.5,
    life: 80,
    ability: "Defensor: aumenta 45 de vida.",
    abilities: [],
    race: "Protoss",
    cost: 250,
    movement: "Ground",
    image: "https://i.ibb.co/zhVHYz8/Sentry.jpg",
  },
  {
    name: "Stalker",
    Gdmg: 9.7,
    Admg: 9.7,
    life: 125,
    ability: "Atacante: daña 9.7 la base enemiga. Defensor: gana 20 de vida.",
    abilities: [],
    race: "Protoss",
    cost: 225,
    movement: "Ground",
    image: "https://i.ibb.co/hYNBxRh/Stalker.jpg",
  },
  {
    name: "Dragoon",
    Gdmg: 12,
    Admg: 12,
    life: 180,
    ability: "Sin habilidad.",
    abilities: [],
    race: "Protoss",
    cost: 225,
    movement: "Ground",
    image: "https://i.ibb.co/YRFMBkf/Dragoon.jpg",
  },
  {
    name: "Dark Templar",
    Gdmg: 37.2,
    Admg: 0,
    life: 120,
    ability: "Atacante: invisible.",
    abilities: [],
    race: "Protoss",
    cost: 375,
    movement: "Ground",
    image: "https://i.ibb.co/pr6krVw/Dark-Templar.jpg",
  },
  {
    name: "Archon",
    Gdmg: 20,
    Admg: 20,
    life: 360,
    ability: "Sin habilidad.",
    abilities: [],
    race: "Protoss",
    cost: 350,
    movement: "Ground",
    image: "https://i.ibb.co/mSc1Zs0/Archon.jpg",
  },
  {
    name: "Immortal",
    Gdmg: 19.2,
    Admg: 0,
    life: 300,
    ability: "Defensor: gana 200 de vida.",
    abilities: [],
    race: "Protoss",
    cost: 475,
    movement: "Ground",
    image: "https://i.ibb.co/kGBHy9H/Immortal.jpg",
  },
  {
    name: "Disruptor",
    Gdmg: 0,
    Admg: 0,
    life: 250,
    ability:
      "Atacante: daña 80 a los enemigos terrestres. Defensor: daña 145 a los enemigos terrestres",
    abilities: [],
    race: "Protoss",
    cost: 450,
    movement: "Ground",
    image: "https://i.ibb.co/K2Fc6Vz/Disruptor.jpg",
  },
  {
    name: "Reaver",
    Gdmg: 25,
    Admg: 0,
    life: 180,
    ability: "Atacante: daña 50 a la base enemiga.",
    abilities: [],
    race: "Protoss",
    cost: 400,
    movement: "Ground",
    image: "https://i.ibb.co/3CVFJM7/Reaver.jpg",
  },
  {
    name: "Colossus",
    Gdmg: 28,
    Admg: 0,
    life: 350,
    ability: "Siempre: es afectado por daño aéreo.",
    abilities: [],
    race: "Protoss",
    cost: 700,
    movement: "Ground",
    image: "https://i.ibb.co/jHN0pHr/Colossus.jpg",
  },
  {
    name: "Observer",
    Gdmg: 0,
    Admg: 0,
    life: 60,
    ability: "Siempre: detector, invisible.",
    abilities: [],
    race: "Protoss",
    cost: 175,
    movement: "Flying",
    image: "https://i.ibb.co/tp4CStJ/Observer.jpg",
  },
  {
    name: "Corsair",
    Gdmg: 0,
    Admg: 12.6,
    life: 180,
    ability: "Sin habilidad.",
    abilities: [],
    race: "Protoss",
    cost: 350,
    movement: "Flying",
    image: "https://i.ibb.co/zRkydd8/Corsair.jpg",
  },
  {
    name: "Arbiter",
    Gdmg: 10,
    Admg: 10,
    life: 350,
    ability: "Siempre: reduce 15% el daño enemigo.",
    abilities: [],
    race: "Protoss",
    cost: 800,
    movement: "Flying",
    image: "https://i.ibb.co/C28jkfS/Arbiter.jpg",
  },
  {
    name: "Void Ray",
    Gdmg: 16.8,
    Admg: 16.8,
    life: 250,
    ability: "Atacante: daña 12.8 la base enemiga.",
    abilities: [],
    race: "Protoss",
    cost: 550,
    movement: "Flying",
    image: "https://i.ibb.co/6RJf84p/Void-Ray.jpg",
  },
  {
    name: "Tempest",
    Gdmg: 17,
    Admg: 12.7,
    life: 300,
    ability: "Atacante: gana 22 de daño terrestre y aéreo.",
    abilities: [],
    race: "Protoss",
    cost: 600,
    movement: "Flying",
    image: "https://i.ibb.co/JCcxscD/Tempest.jpg",
  },
  {
    name: "Carrier",
    Gdmg: 37.3,
    Admg: 37.3,
    life: 450,
    ability: "Atacante: gana 640 de vida.",
    abilities: [],
    race: "Protoss",
    cost: 970,
    movement: "Flying",
    image: "https://i.ibb.co/y6PpWft/Carrier.jpg",
  },
  {
    name: "Mothership",
    Gdmg: 22.8,
    Admg: 22.8,
    life: 700,
    ability: "Siempre: 10 unidades aleatorias son invisibles.",
    abilities: [],
    race: "Protoss",
    cost: 1200,
    movement: "Flying",
    image: "https://i.ibb.co/cg9YMMC/Mothership.jpg",
  },
  {
    name: "Zeratul",
    Gdmg: 75,
    Admg: 75,
    life: 1000,
    ability: "Sin habilidad.",
    abilities: [],
    race: "Protoss",
    cost: 1500,
    movement: "Ground",
    image: "https://i.ibb.co/pRGsnXV/Zeratul.jpg",
  },
];

module.exports = { zergCards, terranCards, protossCards };
