const cardPacks = [
  {
    name: "Criadero Zerg",
    price: 100,
    race: ["Zerg"],
    cards: [
      ["Zergling", "0.3"],
      ["Roach", " 0.2"],
      ["Queen", "0.2"],
      ["Baneling", "0.15"],
      ["Hydralisk", "0.07"],
      ["Ravager", "0.05"],
      ["Lurker", "0.03"],
    ],
    stock: 100,
    image: "https://i.ibb.co/93Qyhg5/packs2-Mesa-de-trabajo-1-copia-7.png",
    amount: 10,
  },
  {
    name: "Colonia Zerg",
    price: 200,
    race: ["Zerg"],
    cards: [
      ["Zergling", "0.05"],
      ["Roach", "0.07"],
      ["Queen", "0.1"],
      ["Baneling", "0.2"],
      ["Hydralisk", "0.19"],
      ["Defiler", "0.13"],
      ["Infestor", "0.13"],
      ["Swarm Host", "0.08"],
      ["Overlord", "0.05"],
    ],
    stock: 100,
    image: "https://i.ibb.co/V274Hh9/packs6-Mesa-de-trabajo-1-copia-7.png",
    amount: 10,
  },
  {
    name: "Colmena de la Supermente",
    price: 300,
    race: ["Zerg"],
    cards: [
      ["Hydralisk", "0.2"],
      ["Defiler", "0.15"],
      ["Infestor", "0.15"],
      ["Swarm Host", "0.12"],
      ["Overlord", "0.1"],
      ["Scourge", "0.08"],
      ["Mutalisk", "0.08"],
      ["Corruptor", "0.06"],
      ["Viper", "0.06"],
    ],
    stock: 100,
    image: "https://i.ibb.co/M2wW9DZ/packs10-Mesa-de-trabajo-1-copia-7.png",
    amount: 10,
  },
  {
    name: "Enjambre de Char",
    price: 500,
    race: ["Zerg"],
    cards: [
      ["Scourge", "0.25"],
      ["Mutalisk", "0.22"],
      ["Corruptor", "0.16"],
      ["Viper", "0.16"],
      ["Ultralisk", "0.09"],
      ["Brood Lord", "0.09"],
      ["Kerrigan", "0.03"],
    ],
    stock: 100,
    image: "https://i.ibb.co/NrKy13k/packs1-Mesa-de-trabajo-1-copia-7.png",
    amount: 10,
  },
  {
    name: "Bunker Terran",
    price: 100,
    race: ["Terran"],
    cards: [
      ["Marine", "0.3"],
      ["Marauder", "0.2"],
      ["Reaper", "0.2"],
      ["Hellion", "0.15"],
      ["Ghost", "0.07"],
      ["Vulture", "0.05"],
      ["Widow Mine", "0.03"],
    ],
    stock: 100,
    image: "https://i.ibb.co/gDNJCX4/packs9-Mesa-de-trabajo-1-copia-7.png",
    amount: 10,
  },
  {
    name: "Estación Planetaria Terran",
    price: 200,
    race: ["Terran"],
    cards: [
      ["Marine", "0.05"],
      ["Marauder", "0.07"],
      ["Reaper", "0.1"],
      ["Hellion", "0.2"],
      ["Ghost", "0.19"],
      ["Goliath", "0.13"],
      ["Siege Tank", "0.13"],
      ["Medivac", "0.08"],
      ["Viking", "0.05"],
    ],
    stock: 100,
    image: "https://i.ibb.co/h8C7hG8/packs7-Mesa-de-trabajo-1-copia-7.png",
    amount: 10,
  },
  {
    name: "Dominio en Korhal",
    price: 300,
    race: ["Terran"],
    cards: [
      ["Ghost", "0.2"],
      ["Goliath", "0.15"],
      ["Siege Tank", "0.15"],
      ["Medivac", "0.12"],
      ["Viking", "0.1"],
      ["Wraith", "0.08"],
      ["Banshee", "0.08"],
      ["Raven", "0.06"],
      ["Liberator", "0.06"],
    ],
    stock: 100,
    image: "https://i.ibb.co/N23pRXy/packs3-Mesa-de-trabajo-1-copia-7.png",
    amount: 10,
  },
  {
    name: "Aliados del Hyperion",
    price: 500,
    race: ["Terran"],
    cards: [
      ["Wraith", "0.25"],
      ["Banshee", "0.22"],
      ["Raven", "0.16"],
      ["Liberator", "0.16"],
      ["Thor", "0.09"],
      ["Battlecruiser", "0.09"],
      ["Raynor", "0.03"],
    ],
    stock: 100,
    image: "https://i.ibb.co/wptZmrx/packs4-Mesa-de-trabajo-1-copia-7.png",
    amount: 10,
  },
  {
    name: "Fanáticos Protoss",
    price: 100,
    race: ["Protoss"],
    cards: [
      ["Zealot", "0.3"],
      ["Sentry", "0.2"],
      ["Stalker", "0.2"],
      ["Dragoon", "0.15"],
      ["Immortal", "0.07"],
      ["Disruptor", "0.05"],
      ["Corsair", "0.03"],
    ],
    stock: 100,
    image: "https://i.ibb.co/K2CYnVY/packs12-Mesa-de-trabajo-1-copia-7.png",
    amount: 10,
  },
  {
    name: "Consejo de Aiur",
    price: 200,
    race: ["Protoss"],
    cards: [
      ["Zealot", "0.05"],
      ["Sentry", "0.07"],
      ["Stalker", "0.1"],
      ["Dragoon", "0.2"],
      ["Immortal", "0.19"],
      ["Dark Templar", "0.13"],
      ["Reaver", "0.13"],
      ["Observer", "0.08"],
      ["Colossus", "0.05"],
    ],
    stock: 100,
    image: "https://i.ibb.co/KGtN3C6/packs11-Mesa-de-trabajo-1-copia-7.png",
    amount: 10,
  },
  {
    name: "Gran Armada Tal'darim",
    price: 300,
    race: ["Protoss"],
    cards: [
      ["Immortal", "0.2"],
      ["Dark Templar", "0.15"],
      ["Reaver", "0.15"],
      ["Observer", "0.12"],
      ["Colossus", "0.1"],
      ["Arbiter", "0.08"],
      ["Void Ray", "0.08"],
      ["Tempest", "0.06"],
      ["Archon", "0.06"],
    ],
    stock: 100,
    image: "https://i.ibb.co/pWTFGcc/packs5-Mesa-de-trabajo-1-copia-7.png",
    amount: 10,
  },
  {
    name: "Memoria del Prelado Tétrico",
    price: 500,
    race: ["Protoss"],
    cards: [
      ["Arbiter", "0.25"],
      ["Void Ray", "0.22"],
      ["Tempest", "0.16"],
      ["Archon", "0.16"],
      ["Carrier", "0.09"],
      ["Mothership", "0.09"],
      ["Zeratul", "0.03"],
    ],
    stock: 100,
    image: "https://i.ibb.co/ph74s8q/packs8-Mesa-de-trabajo-1-copia-7.png",
    amount: 10,
  },
  {
    name: "Entra en el sector Koprulu",
    price: 300,
    race: ["Protoss", "Terran", "Zerg"],
    cards: [
      ["Hydralisk", "0.22"],
      ["Dragoon", "0.22"],
      ["Ghost", "0.22"],
      ["Ultralisk", "0.11"],
      ["Archon", "0.12"],
      ["Thor", "0.11"],
    ],
    stock: 100,
    image: "https://i.ibb.co/3TFnfPJ/packs-Mesa-de-trabajo-1-copia-7.png",
    amount: 10,
  },
];

module.exports = cardPacks;
